name: BR / Compatibility Test

on:
  push:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
  pull_request:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
  label:
    types: [created]

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - name: Check PR labels 
      id: check_pr_labels
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["need-br-compatibility-test"]'

    - run: echo ${{ steps.check_pr_labels.outputs.result }}

    - if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
      uses: actions/checkout@v2

    - name: Set up Go
      if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Generate compatibility test backup data
      if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
      timeout-minutes: 15
      run: sh br/compatibility/prepare_backup.sh

    - name: Start server
      if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
      run: |
        TAG=nightly PORT_SUFFIX=1 docker-compose -f br/compatibility/backup_cluster.yaml rm -s -v
        TAG=nightly PORT_SUFFIX=1 docker-compose -f br/compatibility/backup_cluster.yaml build
        TAG=nightly PORT_SUFFIX=1 docker-compose -f br/compatibility/backup_cluster.yaml up --remove-orphans -d
        TAG=nightly PORT_SUFFIX=1 docker-compose -f br/compatibility/backup_cluster.yaml exec -T control make build_br
        TAG=nightly PORT_SUFFIX=1 docker-compose -f br/compatibility/backup_cluster.yaml exec -T control br/tests/run_compatible.sh run

    - name: Collect component log
      if: ${{ failure() }}
      run: |
        tar czvf ${{ github.workspace }}/logs.tar.gz /tmp/br/docker/backup_logs/*

    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: logs
        path: ${{ github.workspace }}/logs.tar.gz
