name: BR & Lightning 
on:
  push:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
  pull_request:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
  label:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile for ${{ matrix.os }} / ${{ matrix.target}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Check PR labels 
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["needs-br-build-check"]'

      - if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/checkout@v2

      - name: Set up Go
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run build
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        run: make build_tools

  compile-freebsd:
    name: Compile for FreeBSD job
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels 
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["need-br-build-check"]'

      - if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/checkout@v2.1.0

      - name: Set up Go
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Compile for FreeBSD
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        run: GOOS=freebsd make build_tools
